import {
  SiAdobeillustrator,
  SiAdobephotoshop,
  SiAdobepremierepro,
  SiAnaconda,
  SiApacheopenoffice,
  SiArc,
  SiArduino,
  SiBlender,
  SiBrave,
  SiCplusplus,
  SiDbeaver,
  SiDiscord,
  SiEclipseide,
  SiEvernote,
  SiFigma,
  SiFirefox,
  SiGit,
  SiGooglechrome,
  SiIntellijidea,
  SiJavascript,
  SiJupyter,
  SiKrita,
  SiLibreoffice,
  SiMicrosoftedge,
  SiMongodb,
  SiNotion,
  SiOpera,
  SiPostman,
  SiPowerbi,
  SiPycharm,
  SiPython,
  SiSafari,
  SiSketch,
  SiSkype,
  SiSlack,
  SiSpotify,
  SiTableau,
  SiThunderbird,
  SiTorbrowser,
  SiVisualstudiocode,
  SiVivaldi,
  SiVlcmediaplayer,
  SiZoom,
} from "@icons-pack/react-simple-icons";
import { AppWindow, Box, Coffee, IceCreamBowl } from "lucide-react";

// Step 1: Define IconId as a constant object and use `as const` for immutability
export const IconId = {
  VisualStudioCode: "VisualStudioCode",
  JupyterNotebook: "JupyterNotebook",
  AdobePhotoshop: "AdobePhotoshop",
  ArduinoIDE: "ArduinoIDE",
  Slack: "Slack",
  Git: "Git",
  Tableau: "Tableau",
  Sketch: "Sketch",
  Python: "Python",
  Java: "Java",
  CPlusPlus: "CPlusPlus",
  PyCharm: "PyCharm",
  IntelliJIDEA: "IntelliJIDEA",
  Eclipse: "Eclipse",
  PowerBI: "PowerBI",
  Figma: "Figma",
  GoogleChrome: "GoogleChrome",
  Firefox: "Firefox",
  Safari: "Safari",
  Opera: "Opera",
  MicrosoftEdge: "MicrosoftEdge",
  Brave: "Brave",
  Vivaldi: "Vivaldi",
  TorBrowser: "TorBrowser",
  Postman: "Postman",
  MongoDBCompass: "MongoDBCompass",
  Anaconda: "Anaconda",
  Zoom: "Zoom",
  Notion: "Notion",
  AdobeIllustrator: "AdobeIllustrator",
  AdobePremierePro: "AdobePremierePro",
  Spotify: "Spotify",
  VLCMediaPlayer: "VLCMediaPlayer",
  Discord: "Discord",
  Evernote: "Evernote",
  Thunderbird: "Thunderbird",
  Skype: "Skype",
  Krita: "Krita",
  Blender: "Blender",
  OpenOffice: "OpenOffice",
  LibreOffice: "LibreOffice",
  DBeaver: "DBeaver",
  Arc: "Arc",
  Coffee: "Coffee",
  AppWindow: "AppWindow",
  IceCreamBowl: "IceCreamBowl",
  Box: "Box",
} as const;

// Step 2: Infer the type of IconId
export type IconId = keyof typeof IconId;

// Step 3: Create the icon lookup table
export const iconLookup = {
  [IconId.VisualStudioCode]: SiVisualstudiocode,
  [IconId.JupyterNotebook]: SiJupyter,
  [IconId.AdobePhotoshop]: SiAdobephotoshop,
  [IconId.ArduinoIDE]: SiArduino,
  [IconId.Slack]: SiSlack,
  [IconId.Git]: SiGit,
  [IconId.Tableau]: SiTableau,
  [IconId.Sketch]: SiSketch,
  [IconId.Python]: SiPython,
  [IconId.Java]: SiJavascript,
  [IconId.CPlusPlus]: SiCplusplus,
  [IconId.PyCharm]: SiPycharm,
  [IconId.IntelliJIDEA]: SiIntellijidea,
  [IconId.Eclipse]: SiEclipseide,
  [IconId.PowerBI]: SiPowerbi,
  [IconId.Figma]: SiFigma,
  [IconId.GoogleChrome]: SiGooglechrome,
  [IconId.Firefox]: SiFirefox,
  [IconId.Safari]: SiSafari,
  [IconId.Opera]: SiOpera,
  [IconId.MicrosoftEdge]: SiMicrosoftedge,
  [IconId.Brave]: SiBrave,
  [IconId.Vivaldi]: SiVivaldi,
  [IconId.TorBrowser]: SiTorbrowser,
  [IconId.Postman]: SiPostman,
  [IconId.MongoDBCompass]: SiMongodb,
  [IconId.Anaconda]: SiAnaconda,
  [IconId.Zoom]: SiZoom,
  [IconId.Notion]: SiNotion,
  [IconId.AdobeIllustrator]: SiAdobeillustrator,
  [IconId.AdobePremierePro]: SiAdobepremierepro,
  [IconId.Spotify]: SiSpotify,
  [IconId.VLCMediaPlayer]: SiVlcmediaplayer,
  [IconId.Discord]: SiDiscord,
  [IconId.Evernote]: SiEvernote,
  [IconId.Thunderbird]: SiThunderbird,
  [IconId.Skype]: SiSkype,
  [IconId.Krita]: SiKrita,
  [IconId.Blender]: SiBlender,
  [IconId.OpenOffice]: SiApacheopenoffice,
  [IconId.LibreOffice]: SiLibreoffice,
  [IconId.DBeaver]: SiDbeaver,
  [IconId.Arc]: SiArc,
  [IconId.Coffee]: Coffee,
  [IconId.IceCreamBowl]: IceCreamBowl,
  [IconId.AppWindow]: AppWindow,
  [IconId.Box]: Box,
} as const;
