import {
  SiAdobeillustrator,
  SiAdobephotoshop,
  SiAdobepremierepro,
  SiAnaconda,
  SiApacheopenoffice,
  SiArc,
  SiArduino,
  SiBlender,
  SiBrave,
  SiCplusplus,
  SiDbeaver,
  SiDiscord,
  SiEclipseide,
  SiEvernote,
  SiFigma,
  SiFirefox,
  SiGit,
  SiGooglechrome,
  SiIntellijidea,
  SiJavascript,
  SiJupyter,
  SiKrita,
  SiLibreoffice,
  SiMicrosoftedge,
  SiMongodb,
  SiNotion,
  SiOpera,
  SiPostman,
  SiPowerbi,
  SiPycharm,
  SiPython,
  SiSafari,
  SiSketch,
  SiSkype,
  SiSlack,
  SiSpotify,
  SiTableau,
  SiThunderbird,
  SiTorbrowser,
  SiVisualstudiocode,
  SiVivaldi,
  SiVlcmediaplayer,
  SiZoom,
} from "@icons-pack/react-simple-icons";
import { type Application, Category, type Profile } from "../store/types";

export const applications: Application[] = [
  {
    id: "1",
    title: "Visual Studio Code",
    category: Category.Code,
    icon: SiVisualstudiocode,
  },
  {
    id: "2",
    title: "Jupyter Notebook",
    category: Category.Data,
    icon: SiJupyter,
  },
  {
    id: "3",
    title: "Adobe Photoshop",
    category: Category.Design,
    icon: SiAdobephotoshop,
  },
  {
    id: "4",
    title: "Arduino IDE",
    category: Category.Code,
    icon: SiArduino,
  },
  {
    id: "5",
    title: "Slack",
    category: Category.Communication,
    icon: SiSlack,
  },
  {
    id: "6",
    title: "Git",
    category: Category.Code,
    icon: SiGit,
  },
  {
    id: "7",
    title: "Tableau",
    category: Category.Data,
    icon: SiTableau,
  },
  {
    id: "8",
    title: "Sketch",
    category: Category.Design,
    icon: SiSketch,
  },
  {
    id: "9",
    title: "Python (latest)",
    category: Category.Code,
    icon: SiPython,
  },
  {
    id: "10",
    title: "Java (JDK) (latest)",
    category: Category.Code,
    icon: SiJavascript,
  },
  {
    id: "11",
    title: "C++ (latest)",
    category: Category.Code,
    icon: SiCplusplus,
  },
  {
    id: "12",
    title: "PyCharm",
    category: Category.Code,
    icon: SiPycharm,
  },
  {
    id: "13",
    title: "IntelliJ IDEA",
    category: Category.Code,
    icon: SiIntellijidea,
  },
  {
    id: "14",
    title: "Eclipse",
    category: Category.Code,
    icon: SiEclipseide,
  },
  {
    id: "15",
    title: "Power BI",
    category: Category.Data,
    icon: SiPowerbi,
  },
  {
    id: "16",
    title: "Figma",
    category: Category.Design,
    icon: SiFigma,
  },
  {
    id: "17",
    title: "Google Chrome",
    category: Category.Browser,
    icon: SiGooglechrome,
  },
  {
    id: "18",
    title: "Firefox",
    category: Category.Browser,
    icon: SiFirefox,
  },
  {
    id: "19",
    title: "Safari",
    category: Category.Browser,
    icon: SiSafari,
  },
  {
    id: "20",
    title: "Opera",
    category: Category.Browser,
    icon: SiOpera,
  },
  {
    id: "21",
    title: "Microsoft Edge",
    category: Category.Browser,
    icon: SiMicrosoftedge,
  },
  {
    id: "22",
    title: "Brave",
    category: Category.Browser,
    icon: SiBrave,
  },
  {
    id: "23",
    title: "Vivaldi",
    category: Category.Browser,
    icon: SiVivaldi,
  },
  {
    id: "24",
    title: "Tor Browser",
    category: Category.Browser,
    icon: SiTorbrowser,
  },
  {
    id: "25",
    title: "Postman",
    category: Category.Code,
    icon: SiPostman,
  },
  {
    id: "26",
    title: "MongoDB Compass",
    category: Category.Data,
    icon: SiMongodb,
  },
  {
    id: "27",
    title: "Anaconda",
    category: Category.Data,
    icon: SiAnaconda,
  },
  {
    id: "28",
    title: "Zoom",
    category: Category.Communication,
    icon: SiZoom,
  },
  {
    id: "29",
    title: "Notion",
    category: Category.Communication,
    icon: SiNotion,
  },
  {
    id: "30",
    title: "Adobe Illustrator",
    category: Category.Design,
    icon: SiAdobeillustrator,
  },
  {
    id: "31",
    title: "Adobe Premiere",
    category: Category.Design,
    icon: SiAdobepremierepro,
  },
  // Miscellaneous Applications
  {
    id: "32",
    title: "Spotify",
    category: Category.Miscellaneous,
    icon: SiSpotify,
  },
  {
    id: "33",
    title: "VLC Media Player",
    category: Category.Miscellaneous,
    icon: SiVlcmediaplayer,
  },
  {
    id: "34",
    title: "Discord",
    category: Category.Miscellaneous,
    icon: SiDiscord,
  },
  {
    id: "35",
    title: "Evernote",
    category: Category.Miscellaneous,
    icon: SiEvernote,
  },
  {
    id: "36",
    title: "Thunderbird",
    category: Category.Communication,
    icon: SiThunderbird,
  },
  {
    id: "37",
    title: "Skype",
    category: Category.Communication,
    icon: SiSkype,
  },
  {
    id: "38",
    title: "Krita",
    category: Category.Design,
    icon: SiKrita,
  },
  {
    id: "39",
    title: "Blender",
    category: Category.Design,
    icon: SiBlender,
  },
  {
    id: "40",
    title: "OpenOffice",
    category: Category.Miscellaneous,
    icon: SiApacheopenoffice,
  },
  {
    id: "41",
    title: "LibreOffice",
    category: Category.Miscellaneous,
    icon: SiLibreoffice,
  },
  {
    id: "42",
    title: "DBeaver",
    category: Category.Data,
    icon: SiDbeaver,
  },
  {
    id: "43",
    title: "Arc",
    category: Category.Browser,
    icon: SiArc,
  },
];

export const profiles: Profile[] = [
  {
    id: "1",
    title: "Web Developer",
    relevantApplications: [
      "1",
      "6",
      "9",
      "10",
      "12",
      "13",
      "14",
      "17",
      "18",
      "19",
      "25",
    ],
    image: "/avatars/avatar-1.jpg",
  },
  {
    id: "2",
    title: "Data Scientist",
    relevantApplications: [
      "2",
      "7",
      "9",
      "10",
      "15",
      "17",
      "18",
      "26",
      "27",
      "42",
    ],
    image: "/avatars/avatar-11.jpg",
  },
  {
    id: "3",
    title: "Designer",
    relevantApplications: [
      "3",
      "8",
      "16",
      "17",
      "18",
      "20",
      "30",
      "31",
      "38",
      "39",
    ],
    image: "/avatars/avatar-9.jpg",
  },
  {
    id: "4",
    title: "Embedded Developer",
    relevantApplications: ["4", "11", "21", "22"],
    image: "/avatars/avatar-2.jpg",
  },
  {
    id: "5",
    title: "Project Manager",
    relevantApplications: ["5", "23", "24", "28", "29", "36", "37"],
    image: "/avatars/avatar-7.jpg",
  },
  {
    id: "custom",
    title: "Custom",
    relevantApplications: [],
    image: "/avatars/avatar-8.jpg",
  },
];
